apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: url-shortener

images:
  - name: url-shortener-api-dev
    newName: url-shortener-api-dev
    newTag: latest
  - name: url-shortener-client-dev
    newName: url-shortener-client-dev
    newTag: latest
